### ISSUE TITLE
Indent dataset model definition copy by the correct amount to slot right into a model definition

### ISSUE THREAD

**Issue by tg137** [dafnifacility/user-feedback#78]
This would be a really minor quality-of-life thing - when copying YAML for a model definition from a dataset page, could the second line be indented by 12 spaces by default? I think this would match the documentation/default indentation of the model definition YAML for spec > inputs > dataslots > list item > default > list item.

**Comment by tg137** [comment]
Captured in internal ticket https://jira.dafni.rl.ac.uk/browse/CORE-1831

**Comment by roseDickinson** [comment]
This was fixed in v2.4.0.

**Comment by fmcclean** [comment]
I just tested this and it's not fixed for me. Maybe I'm loading a cached version of the page somehow?

**Comment by roseDickinson** [comment]
Hi Fegus, how were you expecting this to work? This issue was informed by Tom Russell who suggested that the indentation should be of the form:
```
- uid: 62a053fe-67da-4ee9-9dc8-ed94d6526f29
            versionUid: c34f37fd-7280-4ab3-8400-21d839271567
```
Which is how the button is working currently. This was to allow for editing YAML files in IDEs that will auto indent the first line but not the second.

**Comment by fmcclean** [comment]
I'm using PyCharm (JetBrains) and it doesn't do any automatic indentation when pasting so the second line ends up being over-indented. No worries if you want to leave it how it is though.

**Comment by roseDickinson** [comment]
Ah I can see why its being over-indented, there was a change to the model definition since this was initially requested thats made the indent 10 spaces rather than 12 spaces. I'll add a task to our backlog so that this can be sorted for the next release

**Comment by fmcclean** [comment]
My last comment was actually wrong. PyCharm/IntelliJ does do automatic indentation and it autocorrects any indention relative to the previous line to be two spaces for YAML. Therefore either 10 or 12 spaces results in the following:

```
- uid: 62a053fe-67da-4ee9-9dc8-ed94d6526f29
    versionUid: c34f37fd-7280-4ab3-8400-21d839271567
```

The only way to get it to paste correctly is to format it like this:

```
- uid: 62a053fe-67da-4ee9-9dc8-ed94d6526f29
  versionUid: c34f37fd-7280-4ab3-8400-21d839271567
```

This may be different for Tom's IDE and it's a very tiny inconvenience but just thought I would clarify.

**Comment by roseDickinson** [comment]
Thanks for that clarification, thats good to know. When the button was first introduced it was formatted as:
```
- uid: 62a053fe-67da-4ee9-9dc8-ed94d6526f29
  versionUid: c34f37fd-7280-4ab3-8400-21d839271567
```
Its clear that when indenting only one line the best indentation to have is different based on the IDE in use. Obviously its wrong at the moment and needs to be fixed. I would propose we either change the button back to:
```
- uid: 62a053fe-67da-4ee9-9dc8-ed94d6526f29
  versionUid: c34f37fd-7280-4ab3-8400-21d839271567
```
Or make the change so both lines are indented correctly:
```
        - uid: 62a053fe-67da-4ee9-9dc8-ed94d6526f29
          versionUid: c34f37fd-7280-4ab3-8400-21d839271567
```
From my perspective the latter would be best since in VSCode (the IDE I use) you can paste both lines in a way to avoid the auto indentation. I don't know if the same is true for Tom's IDE or for PyCharm/IntelliJ.

**Comment by tg137** [comment]
This feature is now unnecessary as we have removed the need for adding the uid and the version uid to the model definition. Instead, users are able to copy _just_ the version UUID from the dataset page.
